naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
  LongMethod:
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated: [ 'Composable' ]

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  ReturnCount:
    excludeGuardClauses: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
